### ISSUE TITLE
invalid arithmetic operator

### ISSUE THREAD

**Issue by Xav-Pe** [alexanderharm/syno-openvpn-static-ip#1]
Hello, 

when using your script I had this error : 

``./synoOpenVpnStaticIp.sh: line 89: 10.8.0.6: syntax error: invalid arithmetic operator (error token is ".8.0.6")``

ipRemote="$((ipLocal-1))"

by replacing with ``echo $ip| awk -F"." '{printf "%d.%d.%d.%d", $1, $2, $3, $4 - 1}'``  It works, but I have another error about these number operations at line 92 :  ``./synoOpenVpnStaticIp.sh: line 92: 10.8.0.6: syntax error: invalid arithmetic operator (error token is ".8.0.6")``. It's about the modulo and I don't have any solution for this.

**Comment by alexanderharm** [comment]
How did you configure the script to run?

**Comment by alexanderharm** [comment]
You only use the the last block of the IP adress, e.g. `synoOpenVpnStaticIp.sh "username:202"`

**Comment by Xav-Pe** [comment]
Ow sorry you're right. It was even the first line of the doc. Sorry and thanks for this script!
